### ISSUE TITLE
Cant't see file on snapmaker

### ISSUE THREAD

**Issue by manojknaikade** [Razor10021990/CuraSnapmakerSender#2] opened 2021-02-18 11:11 UTC
The plugin is detecting the snapmaker and sending the file. I can see the progress bar percentage as the file is transmitting but the file is not visible on the machine's internal storage. The problem started mostly after the firmware update (I am not sure though)
Current Firmware v1.11.4

**Comment by Razor10021990** [comment] 2021-02-19 18:00
I have to look into this. I have not used my printer since the update. But I had this issue while, while developing. If the .gcode file extension misses, the printer does not recognize the file.

**Comment by manojknaikade** [comment] 2021-02-20 07:46
looks like a smaller gcode file is transferring well

**Comment by Razor10021990** [comment] 2021-02-20 08:31
Could you send the model and settings you used, so that I stand a chance to reproduce it.
While testing I also used a very complex and tall model with very fine layer height. Which took over approximately 40 seconds to send. It gave me no problems. But that can change with updates.

**Comment by manojknaikade** [comment] 2021-02-20 08:43
It was working very well for me as. Here is the cura profile
[normal 1.6.curaprofile.zip](https://github.com/Razor10021990/CuraSnapmakerSender/files/6014439/normal.1.6.curaprofile.zip)

**Comment by manojknaikade** [comment] 2021-02-20 09:42
I did some tests with different sizes of gcode files and it seems files of size less than 5 MB are working.

**Comment by PhLohse** [comment] 2021-02-23 13:02
Hi
I get after sending the file the message on the SnapMaker...
[Notification] „Do you want to start the job now?“
Pressing „Yes“ ->
[FabScreen has stopped] „Open app again“

The file also doesn’t show up under „files“ on my SnapMaker. The file I tried is ~2MB.

Using:
Cura 4.8
SnapMaker 2 A350 V1.11.4_20211021

Btw.: Thanks for programming this very useful feature!

**Comment by manojknaikade** [comment] 2021-02-23 14:43
> Hi
> I get after sending the file the message on the SnapMaker...
> [Notification] „Do you want to start the job now?“
> Pressing „Yes“ ->
> [FabScreen has stopped] „Open app again“
> 
> The file also doesn’t show up under „files“ on my SnapMaker. The file I tried is ~2MB.
> 
> Using:
> Cura 4.8
> SnapMaker 2 A350 V1.11.4_20211021
> 
> Btw.: Thanks for programming this very useful feature!

I am getting also FabScreen has stopped error with the latest version of the Plugin I downloaded from Github.
I have to delete all the files sent via the plugin and restart the soapmaker to make it work again.
For time being I am back to USB drive transfer.

**Comment by Razor10021990** [comment] 2021-02-23 19:19
Have you installed the latest version of the repo? I merged a pull request from a Cura dev, who has seen some crashes in their Crash log system. Could be, that this change is not perfect. You could try to install the Version from Cura marketplace and see if those problems don't occur.

It is this version, which you could try to install as well:
https://github.com/Razor10021990/CuraSnapmakerSender/tree/a68981cab8922cd8beb0a0c82ae63c629b18393a

**Comment by Razor10021990** [comment] 2021-02-28 15:01
While prepairng the new Cura Package for release in the Cura Marketplace, i found the error causing this behaviour. A merged pull-request introduced that error. Newest commit is now working again as intended.

**Closed as completed by Razor10021990** 2021-02-28 15:01 UTC

**Comment by manojknaikade** [comment] 2021-03-01 20:07
working again :-) thank you!
